# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
- name: Synapse workspace deployment
  uses: Azure/Synapse-workspace-deployment@V1.5.0
  with:
    # Provide the Synapse workspace name where you want to deploy the artifacts.
    TargetWorkspaceName: foxuat2
    # Specify the path to the workspace artifacts template.
    TemplateFile: foxpoc/template/template.json
    # Specify the path to the template parameter file.
    ParametersFile: foxpoc/template/parameters.json
    # Specify deployment parameter values.
    OverrideArmParameters: # optional, default is 
    # Provide the type of cloud environment. Valid values are: Azure Public, Azure China, Azure US Government, Azure Germany
    Environment: Azure Public
    # Provide the resource group of the target Synapse workspace.
    resourceGroup: I-6772-Analy_CN_could-RG
    # Provide client id of service principal.
    clientId: 8bddc0e3-257b-4918-a3d3-bfd890b2a8a3
    # Provide client secret of the service principal.
    clientSecret: NQq7Q~wGf3wVmH~pbt9iS4biLv4rY6ocqQE0d
    # Provide subscription id.
    subscriptionId: 79d0c17c-c289-49f0-8316-6a287d2ca49b
    # Provide tenant id.
    tenantId: 344bdfb4-c87b-4e12-89e0-df3d631d884d
    # Delete the artifacts which are in the workspace but not in the template.
    DeleteArtifactsNotInTemplate: # optional
    # Use managed identity to generate the bearer token?
    managedIdentity: # optional
    # Deploy managed private endpoints in the template.
    deployManagedPrivateEndpoint: # optional
