name: workspace deployment

on:
    push:
        branches: [ main ]
jobs:
    release:
        # You also can use the self-hosted runners.
        runs-on: windows-latest
        steps:
        # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it.
        - uses: actions/checkout@v2
        - uses: azure/synapse-workspace-deployment@release-1.0
        with:
          TargetWorkspaceName: 'foxpoc2'
          environment: 'Azure Public'
          resourceGroup: 'I-6772-Analy_CN_could-RG'
          subscriptionId: '79d0c17c-c289-49f0-8316-6a287d2ca49b'
          DeleteArtifactsNotInTemplate: 'true'
          managedIdentity: 'False'
